#! /usr/bin/env perl -w
use 5.010;
use strict;
use GameAPI;

my %first_moves;
for my $game (GameAPI->load_games_from_file('games')) {
    my $first_move = @{$game->moves}[0];
    my $first_move_coords = $first_move->normalize_upper_left->as_game_coords;
    my $swap = $game->was_swapped ? '-swap' : '';
    $first_moves{ $first_move_coords . $swap }++;
}

for my $key ( sort {$first_moves{$b} <=> $first_moves{$a}}
              keys %first_moves ) {

    say sprintf("%8s", $key), ": ", $first_moves{$key}
}
