#! /usr/bin/env perl -w
use 5.010;
use strict;
use YAML qw<LoadFile>;

my %first_moves;

for my $game (@{LoadFile("games")}) {
    my $moves = $game->{moves};
    $moves =~ s/;.*//;

    my $col = substr($moves, 2, 1);
    my $row = ord(substr($moves, 3)) - ord("a") + 1;

    if ($row > 7) {
        $row = 14 - $row;
        $col = chr(ord("n") - (ord($col) - ord("a") + 1))
    }

    $first_moves{$col.$row}++
}

for (sort { $first_moves{$b} <=> $first_moves{$a} } keys %first_moves) {
    say $_, ": ", $first_moves{$_}
}
